on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  example-3:
    name: Ex3 Linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: cogent3
           environment-file: doc/rtd-environment.yml
           python-version: 3.7
           condarc-file: doc/condarc.yml
           auto-activate-base: false
      - shell: bash
        run: |
          conda info
          conda list
