on:
  push:
    branches:
      - '*'
    tags:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: MacOS build
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@enh/channels
        with:
           environment-file: doc/rtd-environment.yml
           activate-environment: cogent3
           python-version: 3.7
           channels: conda-forge,plotly
      - name: Build it
        run: |
          make github
