on:
  push:
    branches:
      - '*'
    tags:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: MacOS build
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@enh/channels
        with:
           python-version: 3.7
           condarc-file: doc/condarc.yml
           environment-file: doc/rtd-environment.yml
           activate-environment: cogent3
           auto-activate-base: false
           channels: conda-forge,plotly
      - name: Conda info
        shell: bash
        run: |
            conda info
            conda list
      - name: Build it
        working-directory: doc/
        run: |
          make github
