on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  example-3:
    name: Ex3 Linux
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: cogent3
           environment-file: doc/rtd-environment.yml
           python-version: 3.7
      - shell: bash -l {0}
        run: |
          conda activate cogent3
          conda info
          conda list
